DROP TABLE IF EXISTS wordcount;
CREATE EXTERNAL TABLE wordcount (word STRING, count INT) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' LOCATION '${INPUT}';
INSERT OVERWRITE DIRECTORY '${OUTPUT}' SELECT * FROM wordcount WHERE count > 5;
